# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkd6P43I0XKXKF_sOWqWMRecbM4CFkon
"""

import json
from datetime import datetime

# --- CLASES BASE (Modelos de Datos) ---

class PLADECO:
    def __init__(self, nombre_comuna, periodo, lineamientos):
        self.nombre_comuna = nombre_comuna
        self.periodo = periodo
        self.lineamientos = lineamientos # dict: {"L1": ["O1.1", "O1.2"]}
        self.enfoques = []
        self.marco_seguimiento = {}

class TeoriaDeCambio:
    def __init__(self, nombre, objetivo_pladeco, problema):
        self.nombre = nombre
        self.version = 1.0
        self.objetivo_pladeco = objetivo_pladeco
        self.problema = problema
        self.cadena_causal = {
            "impacto": objetivo_pladeco,
            "resultados": [], # Lista de dicts {"id": "R1", "desc": "...", "tipo": "transformativo"}
            "productos": [],  # Lista de dicts {"id": "P1", "desc": "..."}
            "actividades": [] # Lista de dicts {"id": "A1", "desc": "..."}
        }
        self.supuestos = [] # Lista de dicts {"de": "A1", "a": "P1", "desc": "..."}

class Proyecto:
    def __init__(self, nombre, lider):
        self.nombre = nombre
        self.lider = lider
        self.estado = "Planificado"
        self.progreso = 0
        self.presupuesto_asignado = 0
        self.presupuesto_gastado = 0
        self.actividades_productos = [] # IDs de la TdC

class Portafolio:
    def __init__(self, nombre, tdc_asociada):
        self.nombre = nombre
        self.tdc_asociada = tdc_asociada # Objeto TeoriaDeCambio
        self.proyectos = [] # Lista de objetos Proyecto
        self.riesgos = [] # Lista de dicts {"riesgo": "...", "prob": "Alta", "impacto": "Medio"}

class Indicador:
    def __init__(self, descripcion, resultado_asociado):
        self.descripcion = descripcion
        self.resultado_asociado = resultado_asociado # ID del resultado en la TdC
        self.linea_base = 0
        self.meta = 100
        self.valor_actual = 0
        self.fuente_datos = "Manual" # Puede ser "API: Censo" o "CSV: Encuesta"

    @property
    def avance(self):
        if self.meta == self.linea_base:
            return 100.0 if self.valor_actual >= self.meta else 0.0
        return max(0, min(100, ((self.valor_actual - self.linea_base) / (self.meta - self.linea_base)) * 100))

# --- MÓDULO 1: Diagnóstico y Vinculación con PLADECO ---

class Modulo1_PLADECO:
    def __init__(self):
        self.pladeco_actual = None
        print("Módulo 1: PLADECO inicializado.")

    def vincular_pladeco(self, doc_path):
        print(f"\n--- Vinculando PLADECO desde '{doc_path}' ---")
        # Simulación de extracción de datos de un PDF
        lineamientos = {
            "Desarrollo Económico Sostenible": ["Aumentar empleabilidad juvenil", "Fomentar el turismo local"],
            "Cohesión Social y Calidad de Vida": ["Mejorar espacios públicos", "Reducir la delincuencia"]
        }
        self.pladeco_actual = PLADECO("Villa Esperanza", "2024-2028", lineamientos)

        # Simulación de análisis de IA para Widgets 4 y 5
        self.pladeco_actual.enfoques = ["Género", "Desarrollo Sostenible", "Participación Ciudadana"]
        self.pladeco_actual.marco_seguimiento = {
            "descripcion": "Se mencionan cuentas públicas anuales y reportes semestrales al concejo.",
            "calificacion": "Simple"
        }

        print(f"PLADECO para '{self.pladeco_actual.nombre_comuna}' vinculado exitosamente.")
        print(f"Enfoques detectados: {self.pladeco_actual.enfoques}")
        print(f"Calificación del Marco de Seguimiento: {self.pladeco_actual.marco_seguimiento['calificacion']}")
        return self.pladeco_actual

# --- MÓDULO 2: Diseño de Teoría de Cambio (TdC) Transformativa ---

class Modulo2_TdC:
    def __init__(self, pladeco):
        if not pladeco:
            raise ValueError("El Módulo 2 requiere un PLADECO vinculado.")
        self.pladeco = pladeco
        self.tdc_actual = None
        self.versiones = {}
        print("\nMódulo 2: Teoría de Cambio inicializado.")

    def crear_tdc(self, nombre, objetivo_pladeco, problema):
        print(f"\n--- Creando TdC para el objetivo: '{objetivo_pladeco}' ---")
        self.tdc_actual = TeoriaDeCambio(nombre, objetivo_pladeco, problema)

        # Simulación de construcción de la cadena causal
        self.tdc_actual.cadena_causal["resultados"] = [
            {"id": "R1", "desc": "Jóvenes tienen mejores habilidades para encontrar empleo", "tipo": "convencional"},
            {"id": "R2", "desc": "Empresas locales cambian su percepción y contratan más jóvenes", "tipo": "transformativo"}
        ]
        self.tdc_actual.cadena_causal["productos"] = [
            {"id": "P1", "desc": "Jóvenes con CV mejorado y habilidades de entrevista"},
            {"id": "P2", "desc": "Red de empresas colaboradoras creada"}
        ]
        self.tdc_actual.cadena_causal["actividades"] = [
            {"id": "A1", "desc": "Realizar talleres de habilidades blandas y CV"},
            {"id": "A2", "desc": "Organizar ferias laborales y reuniones con empresarios"}
        ]
        self.tdc_actual.supuestos = [
            {"de": "A1", "a": "P1", "desc": "Los jóvenes asisten y se comprometen con los talleres"},
            {"de": "A2", "a": "R2", "desc": "Los empresarios están abiertos a participar y cambiar su percepción"}
        ]
        print(f"TdC '{nombre}' creada. Contiene {len(self.tdc_actual.supuestos)} supuestos iniciales.")
        return self.tdc_actual

    def guardar_version(self, descripcion):
        version_key = f"v{self.tdc_actual.version}"
        self.versiones[version_key] = {
            "descripcion": descripcion,
            "data": json.loads(json.dumps(self.tdc_actual, default=lambda o: o.__dict__)) # Deep copy
        }
        print(f"Versión '{version_key}' ({descripcion}) guardada.")
        self.tdc_actual.version += 0.1

# --- MÓDULO 3: Planificación y Gestión de Portafolios de Proyectos ---

class Modulo3_Portfolio:
    def __init__(self, tdc):
        if not tdc:
            raise ValueError("El Módulo 3 requiere una TdC.")
        self.tdc = tdc
        self.portafolio_actual = None
        print("\nMódulo 3: Portafolio de Proyectos inicializado.")

    def crear_portafolio(self, nombre):
        print(f"\n--- Creando Portafolio desde la TdC '{self.tdc.nombre}' ---")
        self.portafolio_actual = Portafolio(nombre, self.tdc)

        # Simulación de importación de supuestos como riesgos
        for supuesto in self.tdc.supuestos:
            riesgo = {
                "riesgo": f"Fallo en el supuesto: '{supuesto['desc']}'",
                "prob": "Media",
                "impacto": "Alto",
                "fuente": "TdC Supuesto",
                "estado": "Activo"
            }
            self.portafolio_actual.riesgos.append(riesgo)
        print(f"Importados {len(self.portafolio_actual.riesgos)} riesgos desde los supuestos de la TdC.")

        # Simulación de creación de proyectos
        proyecto1 = Proyecto("Proyecto Capacitación", "Ana Fuentes")
        proyecto1.actividades_productos = ["A1", "P1"]

        proyecto2 = Proyecto("Proyecto Alianzas Empresariales", "Carlos Vera")
        proyecto2.actividades_productos = ["A2", "P2"]

        self.portafolio_actual.proyectos.extend([proyecto1, proyecto2])
        print(f"Creados {len(self.portafolio_actual.proyectos)} proyectos en el portafolio.")
        return self.portafolio_actual

# --- MÓDULO 4: Monitoreo, Evaluación y Aprendizaje (MEL) ---

class Modulo4_MEL:
    def __init__(self, portafolio):
        if not portafolio:
            raise ValueError("El Módulo 4 requiere un Portafolio.")
        self.portafolio = portafolio
        self.indicadores = []
        self.aprendizajes = []
        self.fuentes_datos_conectadas = {}
        print("\nMódulo 4: MEL inicializado.")

    def configurar_indicadores(self):
        print("\n--- Configurando Indicadores de Resultado (GbR) ---")
        # Simula la creación de indicadores para los resultados de la TdC
        for resultado in self.portafolio.tdc_asociada.cadena_causal["resultados"]:
            desc = f"Indicador para '{resultado['desc']}'"
            indicador = Indicador(desc, resultado['id'])
            self.indicadores.append(indicador)
        print(f"Creados {len(self.indicadores)} indicadores.")

    def conectar_fuente_datos(self, nombre, tipo, datos_simulados):
        print(f"Conectando fuente de datos '{nombre}' ({tipo})...")
        self.fuentes_datos_conectadas[nombre] = datos_simulados
        # Simula la vinculación automática a un indicador
        if "delincuencia" in nombre.lower():
            for ind in self.indicadores:
                if "delincuencia" in ind.descripcion.lower():
                    ind.fuente_datos = f"API: {nombre}"
                    ind.valor_actual = datos_simulados["valor_actual"]
                    print(f"Indicador '{ind.descripcion}' vinculado a la fuente de datos '{nombre}'.")

    def registrar_aprendizaje(self, analisis, decision):
        aprendizaje = {
            "fecha": datetime.now().strftime("%Y-%m-%d"),
            "analisis": analisis,
            "decision": decision
        }
        self.aprendizajes.append(aprendizaje)
        print(f"\nNuevo aprendizaje registrado: '{analisis}'")

    def generar_reporte(self, audiencia, nivel_detalle):
        print(f"\n--- Generando Reporte Personalizado ---")
        print(f"Audiencia: {audiencia}, Nivel: {nivel_detalle}")

        reporte = f"**Reporte de Avance - {datetime.now().strftime('%d/%m/%Y')}**\n\n"

        # Resumen Ejecutivo (simulado)
        reporte += "**1. Resumen Ejecutivo**\n"
        reporte += "El portafolio muestra un progreso constante con desafíos clave en la participación empresarial...\n\n"

        # Avance de Indicadores
        if nivel_detalle == "Detallado" or audiencia != "Ciudadanía":
             reporte += "**2. Avance de Indicadores de Resultado**\n"
             for ind in self.indicadores:
                 reporte += f"- {ind.descripcion}: {ind.avance:.1f}% (Valor: {ind.valor_actual}/{ind.meta}, Fuente: {ind.fuente_datos})\n"
             reporte += "\n"

        # Riesgos
        if audiencia in ["Concejo Municipal", "Equipo Interno"]:
            reporte += "**3. Riesgos Principales**\n"
            riesgos_altos = [r for r in self.portafolio.riesgos if r["impacto"] == "Alto"]
            for r in riesgos_altos[:2]: # Mostrar solo los 2 principales
                reporte += f"- {r['riesgo']} (Estado: {r['estado']})\n"
            reporte += "\n"

        # Aprendizajes
        if audiencia == "Equipo Interno":
            reporte += "**4. Aprendizajes Clave**\n"
            for ap in self.aprendizajes:
                reporte += f"- {ap['analisis']} -> Decisión: {ap['decision']}\n"

        # Simulación de visualización geoespacial
        reporte += "\n**5. Visualización Territorial**\n"
        reporte += "[Simulación de mapa de calor mostrando la concentración de actividades del proyecto en la Zona Norte de la comuna]\n"

        print("--- Fin del Reporte ---")
        return reporte

# --- SCRIPT PRINCIPAL DE EJECUCIÓN (main) ---

if __name__ == "__main__":
    # Flujo de trabajo completo

    # 1. Vincular PLADECO
    modulo1 = Modulo1_PLADECO()
    pladeco = modulo1.vincular_pladeco("documentos/pladeco_villa_esperanza.pdf")

    # 2. Crear Teoría de Cambio basada en un objetivo del PLADECO
    objetivo_estrategico = pladeco.lineamientos["Desarrollo Económico Sostenible"][0]
    modulo2 = Modulo2_TdC(pladeco)
    tdc = modulo2.crear_tdc(
        nombre="TdC para Empleabilidad Juvenil",
        objetivo_pladeco=objetivo_estrategico,
        problema="Jóvenes carecen de experiencia laboral relevante."
    )
    modulo2.guardar_version("Borrador inicial para revisión interna")

    # 3. Crear un Portafolio de Proyectos a partir de la TdC
    modulo3 = Modulo3_Portfolio(tdc)
    portafolio = modulo3.crear_portafolio("Portafolio de Empleabilidad Juvenil 2024")

    # 4. Configurar el módulo MEL
    modulo4 = Modulo4_MEL(portafolio)
    modulo4.configurar_indicadores()

    # 5. Simular el paso del tiempo y la actualización de datos
    print("\n... El tiempo pasa, los proyectos se ejecutan ...")
    portafolio.proyectos[0].progreso = 60
    portafolio.proyectos[1].progreso = 30

    # Actualización manual de un indicador
    modulo4.indicadores[0].valor_actual = 50

    # Un riesgo ocurre y se registra un aprendizaje
    portafolio.riesgos[1]["estado"] = "Ocurrido"
    modulo4.registrar_aprendizaje(
        analisis="El supuesto sobre la apertura de los empresarios falló.",
        decision="Crear un programa de incentivos fiscales para empresas que contraten jóvenes."
    )

    # 6. Generar reportes para diferentes audiencias
    reporte_equipo = modulo4.generar_reporte("Equipo Interno", "Detallado")
    print(reporte_equipo)

    reporte_concejo = modulo4.generar_reporte("Concejo Municipal", "Detallado")
    print(reporte_concejo)

    reporte_ciudadania = modulo4.generar_reporte("Ciudadanía", "Resumido")
    print(reporte_ciudadania)